config/routes.rb
Xposers::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions", 
                                       :confirmations => 'confirmations',
                                       :registrations => 'registrations' } do
    get "login", :to => "sessions#new"
    get 'loguit', :to => "sessions#destroy", :as => :logout
    get 'aanmelden', :to => "devise/registrations#new", :as => :register
    get 'gebruiker/wachtwoordkwijt', :to => "devise/passwords#new", :as => :wachtwoordkwijt
    get 'profiel/wachtwoord' => "devise/registrations#edit", :as => :wachtwoord
  end

  resources :abuses, :only => [:index] do
    get :destroy, :on => :member
  end

  scope :module => :forum do
    controller :topic do
      match 'forum/editmessage/:id' => :editmessage, :as => :forumeditmessage
      match 'forum/reportmessage/:id' => :reportmessage, :as => :forumreportmessage
      match 'forum/newtopic/:id' => :new, :as => :newtopic
      match 'forum/edittopic/:id' => :edit, :as => :edittopic
      match 'forum/deletetopic/:id' => :delete, :as => :deletetopic
      match 'forum/movetopic/:id' => :movetopic, :as => :movetopic
      match 'forum/viewreports/:id' => :viewreports, :as => :viewreports
      match 'forum/deletereport/:id' => :deletereport, :as => :deletereport
      match 'forum/topic/newmessage/:id/:cite' => :newmessage
      match 'forum/topic/newmessage/:id' => :newmessage, :as => :forum_newmessage
      match 'forum/topic/new/:id' => :new
      match 'forum/topic/:id/:page' => :index
      match 'forum/topic/:id' => :index, :as => :viewtopic
      match 'forum/topic/:id/:page' => :index, :as => :viewtopicpage

    end
    controller :activetopics do
      match 'forum/activetopics' => :index, :as => :activetopics
      match 'forum/mymessages' => :mymessages, :as => :myforummessages
      match 'forum/mytopics' => :mytopics, :as => :mytopics
    end
    controller :forum do
      match 'forum' => :index, :as => :viewforumindex
      match 'forum/:id' => :subforum, :as => :viewforum
      match 'forum/:id/:page' => :subforum, :as => :viewforumpage
    end
    get 'messages/:id' => 'messages#destroy', :as => :message
  end

  scope :module => :admin do
    controller :home do
      match 'admin' => :index, :as => :admin
    end
    
    controller :users do
      match 'admin/users' => :index, :as => :users
      match 'admin/users/user/:id' => :user
      match 'admin/users/deleteuser/:id' => :deleteuser
      match 'admin/users/csv' => :csv
      match 'admin/users/roles' => :roles
      match 'admin/users/roles/:id' => :role
      match 'admin/users/deletepermission/:id' => :deletepermission
    end
    
    controller :kunst do
      match 'admin/kunst' => :index
      match 'admin/kunst/edittype/:id' => :edittype, :as => :admin_kunst_edittype
      match 'admin/kunst/deletetype/:id' => :deletetype
      match 'admin/kunst/show/:id' => :show
      match 'admin/kunst/createcontainer/:id' => :createcontainer
      match 'admin/kunst/editcontainer/:id' => :editcontainer
      match 'admin/kunst/deletecontainer/:id' => :deletecontainer
      match '/admin/kunst/createproperty/:id' => :createproperty
      match '/admin/kunst/editproperty/:id' => :editproperty
    end
    
    controller :pages do
      match 'admin/page/:id' => :show, :as => :page
    end
    
    controller :aankopen do
      match "admin/aankopen" => :index
      match "admin/aankopen/view/:id" => :view, :as => :aankoop
    end
    
    controller :prefabmail do
      match 'admin/prefabmail' => :index
      match 'admin/prefabmail/edit/:id' => :edit
      match 'admin/prefabmail/delete/:id' => :delete
      match 'admin/prefabmail/create' => :create
      match 'admin/prefabmail/intmails' => :intmails
      match 'admin/prefabmail/editintmail/:id' => :editintmail
    end
    
    controller :forums do
      match 'admin/forums' => :index
      match 'admin/forums/createparentcategory' => :createparentcategory
      match 'admin/forums/createcategory/:id' => :createcategory
      match 'admin/forums/editcategory/:id' => :editcategory
      match 'admin/forums/deletecategory/:id' => :deletecategory
      match 'admin/forums/editforum/:id' => :editforum
      match 'admin/forums/deleteforum/:id' => :deleteforum
      match 'admin/forums/forumpermissions/:id' => :forumpermissions
      match 'admin/forums/createpermission/:id' => :createpermission
      match 'admin/forums/permissions/:id' => :permissions
    end
    
    controller :mailer do
      match 'admin/mailer' => :index
      match 'admin/mailer/delete/:id' => :delete
      match 'admin/mailer/create' => :create
      match 'admin/mailer/deleteall' => :deleteall
    end
    
    controller :webimages do
      match 'admin/webimages' => :index
      match 'admin/webimages/delete/:id' => :delete
    end
    
  end
  
  namespace :admin do
    resources :news, :except => :show
    resources :pages
    resources :rents, only: [:index, :show, :update] do
      get 'mailing', on: :member
      post 'send_email', on: :member
    end
  end
  
  resources :gebruiker, only: [:upload] do
    post :upload, on: :collection
  end

  controller :gebruiker do
    match 'gebruikerprofiel/:id' => :n, :as => :viewprofile
    match 'profiel/avatar' => :avatar, :as => :avatar
    match 'gebruiker/uploadavatar' => :uploadavatar, :as => :uploadavatar
    match 'gebruiker/deleteavatar/:id' => :deleteavatar, :as => :deleteavatar
    match 'gebruiker/setdefaultavatar/:id' => :setdefaultavatar
    match 'profiel/mijnkunst' => :mijnkunst, :as => :mijnkunst
    match 'profiel' => :profiel, :as => :profile
  end

  match 'tellafriend/:id' => "tellafriend#index", :as => :tellafriend

  match 'pagina/:id' => "page#index", as: :pagina

  controller :interieur do
    match 'interieur/upload' => :upload
    match 'interieur'=> :index
    match 'interieur/verwijder/:id' => :verwijder
  end

  controller :kunstenaar do
    match 'kunstenaar/:name/:kunstid/:page' => :index, :as => :werkext
    match 'kunstenaar/:name/:kunstid' => :index, :as => :werk
    match 'kunstenaar/:name' => :show, :as => :kunstenaar
    match 'kunstenaars' => :kunstenaars, :as => :kmenu
    match 'kunstenaars/:page' => :kunstenaars, :as => :kunstenaars
  end

  resources :aankoop, except: [:index, :create, :new, :show, :update] do
    get :order, on: :member
    post :confirm, on: :member
    get :done, on: :member
  end

  resources :closeup, only: :destroy

  scope(:path_names => { new: "nieuw", edit: "wijzig" }) do
    resources :artworks, path: :kunstwerken, only: [:new, :create] do
      get 'verras_me', on: :collection

      resources :rents, path: :huren, only: [:new, :create]
    end
  end
  
  controller :kunst do
    get :misbruik
    post :misbruik

    match 'zoeken' => :search, :as => :search
    match 'zoekresultaten' => :results, :as => :searchresults
    match 'kunst/closeup/:id' => :closeup
    match 'kunst/bekijkwerk/:id' => :bekijkwerk
    match 'kunst/verwijder/:id' => :verwijder
    match 'kunst/wijzig/:id' => :wijzig
    match 'kunst/fav/:id' => :fav
    match 'kunst/app/:id' => :app
    match 'kunst/interieur/:id' => :interieur
    match 'kunst/interieur/:id/:int' => :interieur
    match 'kunst/verwijderreactie/:id' => :verwijderreactie, as: :verwijderreactie
    match 'kunst/wijzigreactie/:id' => :wijzigreactie, as: :wijzigreactie
  end

  resources :xpose, only: [:index, :update]

  controller :xpose do
    match 'xpose/nieuw' => :nieuw, as: :nieuw
    get 'xpose/omzetten' => :omzetten, as: :omzetten
    match 'xpose/plaatsafbeelding/:id' => :plaatsafbeelding, as: :plaatsafbeelding
  end

  controller :site do
    match 'contact' => :contact, :as => :contact
    match 'overxposers' => :overxposers, :as => :overxposers
    match 'disclaimer' => :disclaimer, :as => :disclaimer
  end

  root :to => "site#index"


  #404 error
  match '*path' => "application#rescue_404"

  match ':controller(/:action(/:id(.:format)))'
end

app/views/kunstenaar/_kunstwerk.erb
<h2><%=h @kv.title %></h2>

<% 
if !params[:page] or params[:page].blank? 

  url = ''
  if @ssid and !@ssid.blank?
    if @cp and @cp != 0
      url = url_for werkext_url(:page => 'beschrijving', :name => @kv.user.intname, :kunstid => @kv.id, :ssid => @ssid, :cp => @cp)
      afburl = url_for :controller => 'kunst', :action => 'bekijkwerk', :id => @kv.id, :ssid => @ssid, :cp => @cp
      cafburl = url_for :controller => 'kunst', :action => 'closeup', :id => @kv.id, :ssid => @ssid, :cp => @cp
    else
      url = url_for werkext_url(:page => 'beschrijving', :name => @kv.user.intname, :kunstid => @kv.id, :ssid => @ssid)
      afburl = url_for :controller => 'kunst', :action => 'bekijkwerk', :id => @kv.id, :ssid => @ssid
      cafburl = url_for :controller => 'kunst', :action => 'closeup', :id => @kv.id, :ssid => @ssid
    end
  else
    url = url_for werkext_url(:page => 'beschrijving', :name => @kv.user.intname, :kunstid => @kv.id)
    afburl = url_for :controller => 'kunst', :action => 'bekijkwerk', :id => @kv.id
    cafburl = url_for :controller => 'kunst', :action => 'closeup', :id => @kv.id
  end
%>

  <ul class="knav">
    <li>info</li>

    <% if @kv.closeup_id %>
      <li><%= link_to 'close up', cafburl -%></li>
    <% end -%>

    <li class="noborder"><a href="<%= url %>">beschrijving</a></li>

    <% if @logged_in and (@kv.user_id == @me.id or @me.can('admin')) %>
      <li class="mright noborder"><a href="<%= url_for :controller => 'kunst', :action => 'wijzig', :id => @kv.id -%>">wijzig</a></li>
      <li class="mright"><a href="<%= url_for :controller => 'xpose', :action => 'plaatsafbeelding', :id => @kv.id -%>">wijzig afbeelding</a></li>
      <li class="mright"><a href="<%= url_for :controller => 'kunst', :action => 'verwijder', :id => @kv.id -%>">verwijder</a></li>
    <% end %>
  </ul>

  <% if @kv.kunstimage -%>
    <div class="kimg">
      <a href="<%= afburl %>"><img src="<%= @kv.kunstimage.url('info') %>" alt="<%=h @kv.title -%>" title="<%=h @kv.title -%>" /></a>
    </div>
  <% end -%>

  <div class="kdesc">
    <h4 class="tags">Beschrijving</h4>

    <% 
    bes = sanitize(@kv.description.strip[0..100])
    if @kv.description.size > 100 
      bes = bes + "... " + link_to('lees meer', url)
    end
    %>

    <%= simple_format(bes) -%>
  </div>

  <table id="kinfo">
    <tr>
      <td>
        <span>Kunstenaar</span>
        <p>
          <%= link_to @kv.user.full_name, kunstenaar_url(:name => @kv.user.intname) %>
        </p>
      </td>
      <td><span>Afmetingen</span><p><%=h @kv.width -%>cm x <%=h @kv.height -%>cm <% if !@kv.depth.blank? and @kv.depth > 0 -%> x <%= @kv.depth -%>cm <% end -%></p></td>
      <% if !@kv.type.blank? -%>
      <td><span>Type</span><p><a href="<%= searchresults_url(:type => @kv.type.id) -%>"><%=h @kv.type.title -%></a></p></td>	
      <% end -%>
    </tr>	

	  <% i = 0; i2 = 0; %>

    <% @kv.kunstproperties.each do |kp| %>
      <% if i == 0 %>
        <tr>
      <% end %>

      <% i = i + 1 -%><% i2 = i2 + 1 -%>
          <td><span><%=h kp.propertycontainer.title -%></span><p><a href="<%= searchresults_url(:property => kp.id) -%>"><%=h kp.title -%></a></p></td>
      <% if i == 3 %>
      </tr>
      <% i = 0
        end %>

      <% if @kv.kunstproperties.size == i2 -%>
        </tr>
      <% end %>

    <% end %>

  </table>	

  <% if !@tags.blank? %>
    <h4 class="tags">Trefwoorden</h4>

    <p class="tags2">
      <% @tags.each do |t| %>
      <%= link_to sanitize(t), searchresults_url( :q => sanitize(t)) -%> 
      <% end -%>
    </p>
  <% end %>

  <% if !@kv.material.blank? %>
    <h4 class="tags">Materialen</h4>
    <p class="tags2">
      <% @mats = @kv.material.split(' ') -%>
      
      <% @mats.each do |t| %>
      <%= link_to sanitize(t), searchresults_url( :mat => sanitize(t)) -%> 
      <% end %>
    </p>
  <% end %>

  <ul class="koptions">
    <li id="favo" <% if @fav -%> class="selected" <% end -%>>
      <a href="<%= url_for :controller => 'kunst', :action => 'fav', :id => @kv.id -%>">
        <span>
          <% if @fav %>verwijderen van<% else %> toevoegen aan<% end %> favorietenlijst
        </span>
      </a>
    </li>

    <% if @logged_in and @kv.user_id != @me.id %>
    <li id="appo" <% if @app %> class="selected" <% end %>>
      <a href="<%= url_for :controller => 'kunst', :action => 'app', :id => @kv.id -%>">
        <span>
          <% if @app %>
            ik waardeer dit werk niet meer (<%= @kv.appcount -%> waardering
            <% if @kv.appcount != 1 -%>en<% end %>)
          <% else -%> ik waardeer dit werk (<%= @kv.appcount -%> waardering
            <% if @kv.appcount != 1 -%>en<% end %>)
          <% end %>
        </span>
      </a>
    </li>		
    <% else %>
    <li id="appo" <% if @app %> class="selected" <% end %>>
      <a href="#"><span><%= @kv.appcount %> waardering<% if @kv.appcount != 1 %>en<% end %></span></a>
    </li>
    <% end %>

    <% if !params[:ssid] %>
    <li id="interieur">
      <a href="<%= url_for :controller => 'kunst', :action => 'interieur', :id => @kv.id -%>"><span>bekijk dit werk in mijn interieur</span></a>
    </li>
    <% else %>

      <% if params[:cp] %>
      <li id="interieur">
        <a href="<%= url_for :controller => 'kunst', :action => 'interieur', :id => @kv.id, :cp => params[:cp], :ssid => params[:ssid] -%>"><span>bekijk dit werk in mijn interieur</span></a>
      </li>
      <% else %>
        <li id="interieur">
          <a href="<%= url_for :controller => 'kunst', :action => 'interieur', :id => @kv.id, :ssid => params[:ssid] -%>"><span>bekijk dit werk in mijn interieur</span></a>
        </li>
      <% end %>

    <% end %>

    <li id="tella"><a href="<%= tellafriend_url(:id => @kv.id) -%>"><span>Stuur naar een vriend</span></a></li>

    <li class="artwork-social-button">
      <a href="https://twitter.com/share" class="twitter-share-button" data-lang="nl">Tweeten</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </li>

    <li class="artwork-social-button facebook">
      <div class="fb-like" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
    </li>
  </ul> 

  <div class="prijs">
    <% if @kv.status == 2 %>
      <div class="verkocht"><span>verkocht</span></div>
    <% elsif @kv.status == 1 %>
      <div class="gereserveerd"><span>gereserveerd</span></div>
    <% else %>

      <div class="prices sell">
        <%= button_to "", order_aankoop_path(@kv.id), method: :get %>
        <span class="p">€<%=h @kv.prijs %></span>
      </div>

      <% if @kv.for_rent %>
        <div class="prices rent">
          <%= button_to "", new_artwork_rent_path(@kv.id), method: :get %>
          <span class="p">€<%=h rent_price(@kv.prijs) %></span>
        </div>
      <% end %>

      <p class=shipping-price><%= shipping_info @kv.verzendmethode %></p>
    <% end %>
  </div>
<% 

elsif params[:page] == 'beschrijving'

  url = ''
  if @ssid and !@ssid.blank?
    if @cp and @cp != 0
      url = url_for werk_url(:name => @kv.user.intname, :kunstid => @kv.id, :ssid => @ssid, :cp => @cp)
      cafburl = url_for :controller => 'kunst', :action => 'closeup', :id => @kv.id, :ssid => @ssid, :cp => @cp
    else
      url = url_for werk_url(:name => @kv.user.intname, :kunstid => @kv.id, :ssid => @ssid)
      cafburl = url_for :controller => 'kunst', :action => 'closeup', :id => @kv.id, :ssid => @ssid
    end
  else
    url = url_for werk_url(:name => @kv.user.intname, :kunstid => @kv.id)
    cafburl = url_for :controller => 'kunst', :action => 'closeup', :id => @kv.id
  end
%>

  <ul class="knav">
  	<li><a href="<%= url %>">info</a></li>

  	<% if !@kv.closeup_id.blank? %>
  	<li><a href="<%= cafburl %>">close up</a></li>
  	<% end %>

  	<li class="noborder">beschrijving</li>

  	<% if @kv.user_id == @me.id or @me.can('admin') %>
  	<li class="mright noborder"><a href="<%= url_for :controller => 'kunst', :action => 'wijzig', :id => @kv.id -%>">wijzig</a></li>
  	<li class="mright"><a href="<%= url_for :controller => 'kunst', :action => 'verwijder', :id => @kv.id -%>">verwijder</a></li>
  	<% end %>

  </ul>
  <p>
  	<%= simple_format(sanitize(@kv.description.strip)) %>
  </p>

<% end %>

app/views/kunstenaar/_reacties.erb
<div class="main">

  <div class="h"></div>
  
  <div class="c">

    <h3>Reacties</h3>

    <% if !@kv.replies.blank? -%>

    <ul id="replies">

      <% @reacties.each do |r| %>
      <li>

      <div class="msg">
      <div class="info">
        <p>
        <% if !r.user.voornaam.blank? and !r.user.achternaam.blank? -%>
        <%= link_to sanitize(r.user.voornaam) + " " + sanitize(r.user.achternaam), viewprofile_url(:id => r.user.id)  -%>
        <% else %>
        <%= link_to sanitize(r.user.nickname), viewprofile_url(:id => r.user.id)  -%>
        <% end -%>
        </p>
            <% if !r.user.avatar.blank? -%><%= image_tag(r.user.avatar.url) -%> <% end %>
        </div>
      <p class="m">
        <span><%= Time.parse(r.created_at.to_s).strftime('%d %b %Y %H:%M')%></span>	
      <%= sanitize(r.raw).strip %>
      </p>
      </div>
      <br class="cb">
      <div class="buttons">
        <% if r.user.id == @me.id or @me.can('admin') -%>
          <%= link_to 'wijzig reactie', wijzigreactie_path(r.id) -%>
        <% end -%>

        <% if @me.can('admin') -%>
          | <%= link_to 'verwijder reactie', verwijderreactie_path(r.id) -%>
        <% end -%>
      </div>
      </li>
      <% end %>
    </ul>
    <% if @pagecount > 1 -%>
    <p class="pagination-replies">
    <% i = 0 -%>
    <% while i < @pagecount do -%>
    <% if i == @currentpage %>
      <%= (i + 1).to_s %>
    <% else %>
      <%=link_to (i + 1).to_s, werk_url(:name => @kv.user.intname, :kunstid => @kv.id, :rp => i) -%> 
    <% end -%>
    
    <% i = i + 1 -%>
    <% end -%>
    <p/>
    <% end -%>
    <% else -%>
    <% end -%>
    <% if @logged_in -%>
      <% if @reply %>
        <% if @reply.errors.any? %>
          <ul>
            <% @reply.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
      <h3>Plaats je commentaar</h3>
      <%= form_for :reply do |form| -%>
        <p><%= form.text_area :raw, :rows => 5, :cols => 50, :style => "width: 90%" -%></p>
        <%= form.submit 'Reageren' -%>
      <% end -%>

      <% else -%>
        <p><%= link_to 'Log in', login_url -%> om reacties te plaatsen</p>
      <% end -%>
      <% if @logged_in -%>
      <div id="rapporteermisbruik"><%= link_to 'rapporteer misbruik ', :controller => 'kunst', :action => 'misbruik', :id => @kv.id -%></div>
    <% end -%>			
  </div>
  <div class="s"></div>
</div>

app/views/kunstenaar/index.html.erb
<div class="twocolumn">
  <div class="main">
    <div class="h"></div>
    <div class="c">
      <%= render :partial => 'kunstwerk' %>
    </div>

    <div class="s"></div>
  </div>

  <div class="right">
    <div class="h"></div>
    <div class="c">

      <% if params[:ssid] %>
        <h3>Zoekresultaten</h3>
      <% else %>
        <h3>Andere werken</h3>
      <% end %>

      <div class="imglist">
      <% @kvs.each do |zij|
        url = ''
        if @ssid and !@ssid.blank?
          if @cp and @cp != 0
            url = url_for werk_url(:name => zij.user.intname, :kunstid => zij.id, :ssid => @ssid, :cp => @cp)
          else
            url = url_for werk_url(:name => zij.user.intname, :kunstid => zij.id, :ssid => @ssid)
          end
        else
          url = url_for werk_url(:name => zij.user.intname, :kunstid => zij.id)
        end
      %>
        <% if zij.kunstimage %>
        <a href="<%= url %>"><img src="<%= zij.kunstimage.url('square_small') %>" /></a>
        <% end -%>
      <% end %>
      </div>

    </div>
    <div class="s"></div>		
  </div>
  <%= render :partial => 'reacties' %>
</div>

app/views/kunstenaar/kunstwerk.html.erb
<% if !@kvs.blank? %>
<div class="twocolumn">
				<div class="main">
					<div class="h"></div>
					<div class="c"><%= render :partial => 'kunstwerk' %></div>
					<div class="s"></div>
				</div>
				<div class="right">
					<div class="h"></div>
					<div class="c">
						<% if params[:ssid] %>
						<h3>Zoekresultaten</h3>
						<% else %>
						<h3>Andere werken</h3>
						<% end %>
						<div class="imglist">
					<% @kvs.each do |zij| %>
					<%
					url = ''
					if @ssid and !@ssid.blank?
						if @cp and @cp != 0
							url = url_for werk_url(:name => zij.user.intname, :kunstid => zij.id, :ssid => @ssid, :cp => @cp)
						else
							url = url_for werk_url(:name => zij.user.intname, :kunstid => zij.id, :ssid => @ssid)
						end
					else
						url = url_for werk_url(:name => zij.user.intname, :kunstid => zij.id)
					end
					-%>
					<% if zij.kunstimage -%>
					<a href="<%= url %>"><img src="<%= zij.kunstimage.url('square_small') %>" /></a>
					<% end -%>
					<% end %>
						</div>
					</div>
					<div class="s"></div>		
				</div>
<%= render :partial => 'reacties' %>
</div>
<% end %>

app/views/kunstenaar/show.html.erb
<div class="wide">
  <div class="h"></div>

    <div class="c">
      <h2><%=h complete_username(@kunstenaar) %></h2>

      <% if @me.isrole('kunstenaar') and @me.id == @kunstenaar.id -%>
        <p><%= link_to 'Wijzigen', profile_url -%></p>
      <% end %>

      <% if !@kunstenaar.avatar.blank? -%>
        <%= image_tag(@kunstenaar.avatar.url, :class => 'k-avatar') -%>
      <% end -%>

      <% if !@kunstenaar.profile_geboorteplaats.blank? -%>
      <p>
        <%=h @kunstenaar.profile_geboorteplaats %><%=h ", #{@kunstenaar.profile_geboortedatum}" if !@kunstenaar.profile_geboortedatum.blank? %>
      </p>
      <% end %>
      
      <% if !@kunstenaar.profile_description.blank? -%>
      <p><%=h @kunstenaar.profile_description.strip -%></p>
      <% end -%>

      <% if !@opleidingen.blank? -%>
      <h3>Opleiding<% if @opleidingen.size > 1 -%>en<% end -%></h3>
      <ul>
        <% @opleidingen.each do |o| -%>
        <li><%=h o -%></li>
        <% end -%>
      </ul>
      <% end -%>
      <% if !@disciplines.blank? -%>
      <h3>Discipline<% if @disciplines.size > 1 -%>s<% end -%></h3>
      <ul>
        <% @disciplines.each do |disc| -%>
        <li><%=h disc -%></li>
        <% end -%>
      </ul>
      <% end -%>
      <% if !@pcv.blank? -%>
      <h3>CV</h3>
      <ul>
        <% @pcv.each do |cv| -%>
        <li><%=h cv -%></li>
        <% end -%>
      </ul>
      <% end -%>
      <% if !@pexpo.blank? -%>
      <h3>Exposities</h3>
      <ul>
        <% @pexpo.each do |expo| -%>
        <li><%=h expo -%></li>
        <% end -%>
      </ul>
      <% end -%>
      <% if !@pawards.blank? -%>
      <h3>Prijzen en awards</h3>
      <ul>
        <% @pawards.each do |award| -%>
        <li><%=h award -%></li>
        <% end -%>
      </ul>
      <% end -%>
      <% if !@kunstenaar.profile_website.blank? and (@kunstenaar.profile_website[0..6] == 'http://' or @kunstenaar.profile_website[0..3] == 'www') -%>
      <h3>Website</h3>
      <% if @kunstenaar.profile_website[0..6] == 'http://' -%>
      <%= link_to sanitize(@kunstenaar.profile_website), sanitize(@kunstenaar.profile_website), {:popup => true }-%>
      <% else -%>
      <%= link_to 'http://' + sanitize(@kunstenaar.profile_website), 'http://' + sanitize(@kunstenaar.profile_website),  :popup => true -%>
      <% end -%>
      <% end -%>
    </div>
  <div class="s"></div>
  </div>
  <div class="wide">
  <div class="h"></div>

  <div class="c">
    <h2>Werk van <%=h complete_username(@kunstenaar) %></h2>
    <ul id="sresults">
      <% @kvs.each do |kv| %>
      <li>
        <% if kv.kunstimage %>
          <a href="<%= url_for werk_url(:name => kv.user.intname, :kunstid => kv.id) %>">
            <img src="<%= kv.kunstimage.url('square') %>" />
          </a>
        <% end %>
        <div class="info">
          <h4><a href="<%= url_for werk_url(:name => kv.user.intname, :kunstid => kv.id, :ssid => @ssid, :cp => @cp) %>"><%=h kv.title.strip[0..17] -%><% if kv.title.size > 17 -%>...<% end -%></a></h4>
        <span class="waarderingen"><%= kv.appcount %> waardering<% if kv.appcount != 1 %>en<% end -%></span>
        </div>
      </li>
      <% end %>
    </ul>
    <% if @pagecount > 1 -%>
    <p class="pagination-search">
    <% i = 0 %>
    <% while i < @pagecount do %>
    <%=link_to (i + 1).to_s, kunstenaar_url(:name => @kunstenaar.intname, :page => i) %> 
    <% i = i + 1 %>
    <% end %>
    <p/>
    <% end %>
    <br style="clear: both;" />
  </div>
  <div class="s"></div>
</div>