config/routes.rb
Xposers::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions", 
                                       :confirmations => 'confirmations',
                                       :registrations => 'registrations' } do
    get "login", :to => "sessions#new"
    get 'loguit', :to => "sessions#destroy", :as => :logout
    get 'aanmelden', :to => "devise/registrations#new", :as => :register
    get 'gebruiker/wachtwoordkwijt', :to => "devise/passwords#new", :as => :wachtwoordkwijt
    get 'profiel/wachtwoord' => "devise/registrations#edit", :as => :wachtwoord
  end

  resources :abuses, :only => [:index] do
    get :destroy, :on => :member
  end

  scope :module => :forum do
    controller :topic do
      match 'forum/editmessage/:id' => :editmessage, :as => :forumeditmessage
      match 'forum/reportmessage/:id' => :reportmessage, :as => :forumreportmessage
      match 'forum/newtopic/:id' => :new, :as => :newtopic
      match 'forum/edittopic/:id' => :edit, :as => :edittopic
      match 'forum/deletetopic/:id' => :delete, :as => :deletetopic
      match 'forum/movetopic/:id' => :movetopic, :as => :movetopic
      match 'forum/viewreports/:id' => :viewreports, :as => :viewreports
      match 'forum/deletereport/:id' => :deletereport, :as => :deletereport
      match 'forum/topic/newmessage/:id/:cite' => :newmessage
      match 'forum/topic/newmessage/:id' => :newmessage, :as => :forum_newmessage
      match 'forum/topic/new/:id' => :new
      match 'forum/topic/:id/:page' => :index
      match 'forum/topic/:id' => :index, :as => :viewtopic
      match 'forum/topic/:id/:page' => :index, :as => :viewtopicpage

    end
    controller :activetopics do
      match 'forum/activetopics' => :index, :as => :activetopics
      match 'forum/mymessages' => :mymessages, :as => :myforummessages
      match 'forum/mytopics' => :mytopics, :as => :mytopics
    end
    controller :forum do
      match 'forum' => :index, :as => :viewforumindex
      match 'forum/:id' => :subforum, :as => :viewforum
      match 'forum/:id/:page' => :subforum, :as => :viewforumpage
    end
    get 'messages/:id' => 'messages#destroy', :as => :message
  end

  scope :module => :admin do
    controller :home do
      match 'admin' => :index, :as => :admin
    end
    
    controller :users do
      match 'admin/users' => :index, :as => :users
      match 'admin/users/user/:id' => :user
      match 'admin/users/deleteuser/:id' => :deleteuser
      match 'admin/users/csv' => :csv
      match 'admin/users/roles' => :roles
      match 'admin/users/roles/:id' => :role
      match 'admin/users/deletepermission/:id' => :deletepermission
    end
    
    controller :kunst do
      match 'admin/kunst' => :index
      match 'admin/kunst/edittype/:id' => :edittype, :as => :admin_kunst_edittype
      match 'admin/kunst/deletetype/:id' => :deletetype
      match 'admin/kunst/show/:id' => :show
      match 'admin/kunst/createcontainer/:id' => :createcontainer
      match 'admin/kunst/editcontainer/:id' => :editcontainer
      match 'admin/kunst/deletecontainer/:id' => :deletecontainer
      match '/admin/kunst/createproperty/:id' => :createproperty
      match '/admin/kunst/editproperty/:id' => :editproperty
    end
    
    controller :pages do
      match 'admin/page/:id' => :show, :as => :page
    end
    
    controller :aankopen do
      match "admin/aankopen" => :index
      match "admin/aankopen/view/:id" => :view, :as => :aankoop
    end
    
    controller :prefabmail do
      match 'admin/prefabmail' => :index
      match 'admin/prefabmail/edit/:id' => :edit
      match 'admin/prefabmail/delete/:id' => :delete
      match 'admin/prefabmail/create' => :create
      match 'admin/prefabmail/intmails' => :intmails
      match 'admin/prefabmail/editintmail/:id' => :editintmail
    end
    
    controller :forums do
      match 'admin/forums' => :index
      match 'admin/forums/createparentcategory' => :createparentcategory
      match 'admin/forums/createcategory/:id' => :createcategory
      match 'admin/forums/editcategory/:id' => :editcategory
      match 'admin/forums/deletecategory/:id' => :deletecategory
      match 'admin/forums/editforum/:id' => :editforum
      match 'admin/forums/deleteforum/:id' => :deleteforum
      match 'admin/forums/forumpermissions/:id' => :forumpermissions
      match 'admin/forums/createpermission/:id' => :createpermission
      match 'admin/forums/permissions/:id' => :permissions
    end
    
    controller :mailer do
      match 'admin/mailer' => :index
      match 'admin/mailer/delete/:id' => :delete
      match 'admin/mailer/create' => :create
      match 'admin/mailer/deleteall' => :deleteall
    end
    
    controller :webimages do
      match 'admin/webimages' => :index
      match 'admin/webimages/delete/:id' => :delete
    end
    
  end
  
  namespace :admin do
    resources :news, :except => :show
    resources :pages
    resources :rents, only: [:index, :show, :update] do
      get 'mailing', on: :member
      post 'send_email', on: :member
    end
  end
  
  resources :gebruiker, only: [:upload] do
    post :upload, on: :collection
  end

  controller :gebruiker do
    match 'gebruikerprofiel/:id' => :n, :as => :viewprofile
    match 'profiel/avatar' => :avatar, :as => :avatar
    match 'gebruiker/uploadavatar' => :uploadavatar, :as => :uploadavatar
    match 'gebruiker/deleteavatar/:id' => :deleteavatar, :as => :deleteavatar
    match 'gebruiker/setdefaultavatar/:id' => :setdefaultavatar
    match 'profiel/mijnkunst' => :mijnkunst, :as => :mijnkunst
    match 'profiel' => :profiel, :as => :profile
  end

  match 'tellafriend/:id' => "tellafriend#index", :as => :tellafriend

  match 'pagina/:id' => "page#index", as: :pagina

  controller :interieur do
    match 'interieur/upload' => :upload
    match 'interieur'=> :index
    match 'interieur/verwijder/:id' => :verwijder
  end

  controller :kunstenaar do
    match 'kunstenaar/:name/:kunstid/:page' => :index, :as => :werkext
    match 'kunstenaar/:name/:kunstid' => :index, :as => :werk
    match 'kunstenaar/:name' => :show, :as => :kunstenaar
    match 'kunstenaars' => :kunstenaars, :as => :kmenu
    match 'kunstenaars/:page' => :kunstenaars, :as => :kunstenaars
  end

  resources :aankoop, except: [:index, :create, :new, :show, :update] do
    get :order, on: :member
    post :confirm, on: :member
    get :done, on: :member
  end

  resources :closeup, only: :destroy

  scope(:path_names => { new: "nieuw", edit: "wijzig" }) do
    resources :artworks, path: :kunstwerken, only: [:new, :create] do
      get 'verras_me', on: :collection

      resources :rents, path: :huren, only: [:new, :create]
    end
  end
  
  controller :kunst do
    get :misbruik
    post :misbruik

    match 'zoeken' => :search, :as => :search
    match 'zoekresultaten' => :results, :as => :searchresults
    match 'kunst/closeup/:id' => :closeup
    match 'kunst/bekijkwerk/:id' => :bekijkwerk
    match 'kunst/verwijder/:id' => :verwijder
    match 'kunst/wijzig/:id' => :wijzig
    match 'kunst/fav/:id' => :fav
    match 'kunst/app/:id' => :app
    match 'kunst/interieur/:id' => :interieur
    match 'kunst/interieur/:id/:int' => :interieur
    match 'kunst/verwijderreactie/:id' => :verwijderreactie, as: :verwijderreactie
    match 'kunst/wijzigreactie/:id' => :wijzigreactie, as: :wijzigreactie
  end

  resources :xpose, only: [:index, :update]

  controller :xpose do
    match 'xpose/nieuw' => :nieuw, as: :nieuw
    get 'xpose/omzetten' => :omzetten, as: :omzetten
    match 'xpose/plaatsafbeelding/:id' => :plaatsafbeelding, as: :plaatsafbeelding
  end

  controller :site do
    match 'contact' => :contact, :as => :contact
    match 'overxposers' => :overxposers, :as => :overxposers
    match 'disclaimer' => :disclaimer, :as => :disclaimer
  end

  root :to => "site#index"


  #404 error
  match '*path' => "application#rescue_404"

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/admin/forums_controller.rb
class Admin::ForumsController < ApplicationController
  before_filter :require_admin
  layout 'admin'

  def index
    @forums = Forumparentcategory.find(:all, :include => 'forumcategories')
    @title = 'Forums'
  end
  def createparentcategory
    if !params[:parentcategory][:title].blank?
      Forumparentcategory.create(:title => params[:parentcategory][:title])
    else
      flash[:notice] = "Titel is leeg"
    end
    redirect_to :action => 'index'
  end
  def createcategory
    if !params[:forumcategory][:title].blank?
      fp = Forumcategory.create(params[:forumcategory])
      fp.update_attribute('forumparentcategory_id', params[:id])
    else
      flash[:notice] = "Titel is leeg"
    end
    redirect_to :action => 'index'
  end
  def editcategory
    if params[:id]
      @category = Forumparentcategory.find(params[:id])
      @title = @category.title
      if request.post?
        if !params[:category][:title].blank?
          @category.update_attribute('title', params[:category][:title])
        end
        redirect_to :action => 'index'
      end
    else
      hit_error(404)
    end
  end
  def deletecategory
    if params[:id]
      @category = Forumparentcategory.find(params[:id])
      @title = "Delete " + @category.title
      
      if request.post?
        @category.destroy
        redirect_to :action => 'index'
      end
    else
      hit_error(404)
    end
  end
  def editforum
    if !params[:id]
      hit_error(404)
    end
    @forumcategory = Forumcategory.find(params[:id])
    @title = @forumcategory.title
    if request.post?
      @forumcategory.update_attributes(params[:forumcategory])
      redirect_to :action => 'index'
    end
  end
  def deleteforum
    if !params[:id]
      hit_error(404)
    end
    @forum = Forumcategory.find(params[:id])
    if request.post?
      @forum.destroy
      flash['notice'] = 'Deleted forum'
      redirect_to :action => 'index'
    end
  end
  def forumpermissions
    @forum = Forumcategory.find(params[:id])
    @roles = Role.find(:all)
    @title = @forum.title
    @permissions = Forumpermission.find(:all, :conditions => 'parent_id = ' + @forum.id.to_s, :include => :role)
    if request.post? || request.put?
      if params[:forumpermission][:permission_id]
        #@permission = Forumpermission.find_by_id(params[:permission][:permission_id])
        #@permission.update_attributes(:action => params[:permission][:action], :role_id => params[:permission][:role_id], :can => params[:permission][:can])
        @permission = Forumpermission.find(params[:forumpermission][:permission_id])
        @permission.update_attributes(params[:forumpermission].except(:permission_id))
        redirect_to :action => 'forumpermissions', :id => params[:id]
      end
    end
  end
  def createpermission
    if params[:id]
      # permission for special forum
      Forumpermission.create(:action => params[:permission][:action], :mode => 'forum', :can => params[:permission][:can], :role_id => params[:permission][:role_id], :parent_id => params[:id])
      redirect_to :action => 'forumpermissions', :id => params[:id]
    else
      Forumpermission.create(:action => params[:permission][:action], :mode => 'board', :can => params[:permission][:can], :role_id => params[:permission][:role_id], :parent_id => '0')
      redirect_to :action => 'permissions'
  
    end
  end
  def permissions
    @permissions = Forumpermission.find(:all, :conditions => "mode = 'board'", :include => :role)
    @roles = Role.find(:all)
    @title = 'Permissions'
    if request.post? || request.put?
      @permission = Forumpermission.find(params[:forumpermission][:id])
      @permission.update_attributes(params[:forumpermission])
      redirect_to :action => 'permissions'
    end
  end
end

app/controllers/forum/activetopics_controller.rb
class Forum::ActivetopicsController < ApplicationController
  layout 'forum'
  before_filter :forum_permissions

  def index
    @title = 'Actieve topics'
    okfora = []
    @topics = []
    
    @pcat = Forumparentcategory.find(:all, :select => 'forumparentcategories.id AS cat_id, forumparentcategories.title AS cat_title, forumcategories.*, users.nickname AS last_reply_user_nickname', :order => 'forumparentcategories.id ASC', :joins => 'INNER JOIN forumcategories ON forumcategories.forumparentcategory_id = forumparentcategories.id LEFT JOIN users ON users.id = forumcategories.lastreply_user_id')
    @forums = Hash.new{|h,k| h[k]=Hash.new(&h.default_proc) }
    @pcat.each do |p|
      if @me.role.forum_can('view', 'forum', p.id)
        okfora.push p.id
      end
    end
    #pagination thing
    if params[:page]
      page = params[:page]
    else
      page = nil
    end
    @topics = Forumtopic.paginate(:page => page, :select => "forumtopics.*, users.nickname", :joins => "inner join users on users.id = forumtopics.user_id", :conditions => " forumcategory_id IN(" + okfora.join(',') + ")", :per_page => 50, :order => 'forumtopics.lastreply_user_datetime DESC, forumtopics.created_at DESC')
  end

  def mytopics
    @title = 'Mijn topics'
    okfora = []
    @topics = []
    
    @pcat = Forumparentcategory.find(:all, :select => 'forumparentcategories.id AS cat_id, forumparentcategories.title AS cat_title, forumcategories.*, users.nickname AS last_reply_user_nickname', :order => 'forumparentcategories.id ASC', :joins => 'INNER JOIN forumcategories ON forumcategories.forumparentcategory_id = forumparentcategories.id LEFT JOIN users ON users.id = forumcategories.lastreply_user_id')
    @forums = Hash.new{|h,k| h[k]=Hash.new(&h.default_proc) }
    @pcat.each do |p|
      if @me.role.forum_can('view', 'forum', p.id)
        okfora.push p.id
      end
    end
    #pagination thing
    if params[:page]
      page = params[:page]
    else
      page = nil
    end
    @topics = Forumtopic.paginate(:page => page, :select => "forumtopics.*, users.nickname", :joins => "inner join users on users.id = forumtopics.user_id", :conditions => " forumcategory_id IN(" + okfora.join(',') + ") AND forumtopics.user_id = " + @me.id.to_s, :per_page => 50, :order => 'forumtopics.lastreply_user_datetime DESC, forumtopics.created_at DESC')
  end

  def mymessages
    @title = 'Mijn berichten'
    okfora = []
    @topics = []
    
    @pcat = Forumparentcategory.find(:all, 
      :select => 'forumparentcategories.id AS cat_id, forumparentcategories.title AS cat_title, forumcategories.*, users.nickname AS last_reply_user_nickname', 
      :order => 'forumparentcategories.id ASC', 
      :joins => 'INNER JOIN forumcategories ON forumcategories.forumparentcategory_id = forumparentcategories.id LEFT JOIN users ON users.id = forumcategories.lastreply_user_id')
    @forums = Hash.new{|h,k| h[k]=Hash.new(&h.default_proc) }
    @pcat.each do |p|
      if @me.role.forum_can('view', 'forum', p.id)
        okfora.push p.id
      end
    end
    #pagination thing
    if params[:page]
      page = params[:page]
    else
      page = nil
    end
    @topics = Forumtopic.paginate(:page => page, 
      :select => "forumtopics.*, users.nickname", 
      :joins => "inner join users on users.id = forumtopics.user_id inner join forummessages on forummessages.forumtopic_id = forumtopics.id", 
      :conditions => " forumcategory_id IN(" + okfora.join(',') + ") AND (forummessages.user_id = #{@me.id} OR forumtopics.user_id = #{@me.id})" , 
      :per_page => 50, 
      :group => 'users.id, forumtopics.id', 
      :order => 'forumtopics.lastreply_user_datetime DESC, forumtopics.created_at DESC')
  end
end

app/controllers/forum/forum_controller.rb
class Forum::ForumController < ApplicationController
  layout 'forum'
  before_filter :forum_permissions

  def index
    @title = 'Forum'
    @parent_categories = Forumparentcategory.includes(:forumcategories, :user)
                                            .order('forumparentcategories.id ASC')

    @forums = Hash.new { |h,k| h[k] = Hash.new(&h.default_proc) }

    @parent_categories.each do |parent|
      @forums[parent.id]['parent'] = parent

      parent.forumcategories.each do |category|
        if @me.role.forum_can('view', 'forum', category.id)
          @forums[parent.id]['categories'][category.id] = category
        end
      end
    end
  end

  def subforum
    if !params[:id] or !is_a_number?(params[:id])
      redirect_to root_url, notice: "De door u gezochte pagina bestaat niet." and return
    end

    @forum = Forumcategory.find(params[:id])
    @title = @forum.title

    if !@me.role.forum_can('view', 'forum', @forum.id)
      hit_error(403) and return
    end

    @breadcrumbs = [:s1 => {:title => @forum.title}]
    
    @topics = Forumtopic.paginate(:page => params[:page],
                                  :select => "forumtopics.*, users.nickname, u2.nickname AS last_reply_user_nickname",
                                  :joins => "inner join users on users.id = forumtopics.user_id left join users u2 on u2.id = forumtopics.lastreply_user_id",
                                  :conditions => " forumcategory_id  = " + sanitize_int(params[:id]),
                                  :per_page => 50,
                                  :order => 'forumtopics.lastreply_user_datetime DESC, forumtopics.created_at DESC')
  end
end

app/views/forum/forum/_breadcrumbs.html.erb
<ul id="breadcrumbs">
  <li><%= link_to 'Les Forums', viewforumindex_url %></li>
</ul>

app/views/forum/forum/index.html.erb
<ul id="forumhead">
  <li class="top">
    <ul>
      <li class="tinfo">Forum</li>
    </ul>
  </li>
  <li class="bottom">
    <ul class="forummenu">
      <%= render :partial => "forum/menu" -%>
    </ul>
  </li>
</ul>

<% @forums.each do |wtf, parent_category| %>

  <% if parent_category['categories'].size > 0 %>
    <table id="forum_list">
      <thead>
        <tr>
          <th class="title" colspan="2"><%= h parent_category['parent'].title %></th>
          <th>Topics</th>
          <th>Berichten</th>
          <th>Laatste bericht</th>
          <th class="last">Moderators</th>
        </tr>
      </thead>

      <tbody>
        <% parent_category['categories'].each do |wtf, category| %>
          <tr class="topic">

            <td class="forum_image">
              <% unless category.lastreply_at %>
                <% if Time.parse(category.lastreply_at) > Time.parse(2.days.ago.to_s) -%>
                  <%= image_tag('forum_topic_active.png') %>
                <% else %>
                  <%= image_tag('forum_topic_normal.png') %>
                <% end %>
              <% else %>
                  <%= image_tag('forum_topic_normal.png') %>
              <% end %>
            </td>

            <td class="title">
              <strong><%= link_to category.title, viewforum_url(:id => category.id) %></strong>
            </td>

            <td><%=h category.forumtopics.count %></td>
            <td><%=h category.forummessages.count %></td>
            <td><%=h category.forummessages.last.user.nickname if category.forummessages.count > 0 %></td>
            <td><%=h category.moderators %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>

<ul id="topichead">
  <li class="tinfo">Forum</li>
</ul>

app/views/forum/forum/subforum.html.erb
<ul id="forumhead">
  <li class="top">
    <ul>
      <li class="tinfo"><%= link_to 'Forum', viewforumindex_url %> > <%= @forum.title %></li>
    </ul>
  </li>
  <li class="bottom">
    <ul>
      <%= render :partial => "forum/menu" -%>
      <li class="pages">
		<% if @me.role.forum_can('newtopic', 'forum', @forum.id) %><div class="finfo"><%= link_to 'Nieuw topic', newtopic_url(:id => @forum.id) %></div><% end %>
	 </li>
    </ul>
  </li>
</ul>


<table id="forum_list">
  <thead class="topics">
    <tr>
      <th class="title" colspan="2">Titel</th>
      <th>Berichten</th>
      <th>Auteur</th>
	    <th>Laatste Bericht</th>
      <th class="last">Op</th>
    </tr>
  </thead>
  <tbody>
    <% if @topics.blank? %>
      <tr>
        <td colspan="5">Geen topics in dit forum</td>
      </tr>
    <% end %>

    <% @topics.each do |t| %>
      <tr class="topic">
        <td class="forum_image">
          <% if t.ttype == 'announcement' -%>
            <%= image_tag('forum_topic_announcement.png') -%>
          <% elsif t.ttype == 'sticky' -%>
            <%= image_tag('forum_topic_sticky.png') -%>
          <% else %>
            <% if t.locked %>
              <%= image_tag('forum_topic_locked.jpg') -%>
            <% elsif t.lastreply_user_datetime != nil %>
              <% if t.lastreply_user_datetime > Time.parse(2.days.ago.to_s) -%>
              <%= image_tag('forum_topic_active.png') -%>
              <% else %>
              <%= image_tag('forum_topic_normal.png') -%>
              <% end -%>
            <% else -%>
              <%= image_tag('forum_topic_normal.png') -%>
            <% end -%>
          <% end -%>
        </td>

        <td class="title">
          <%= link_to sanitize(t.title), viewtopic_url(:id => t.id) -%>
          <% if t.message_count > 20 -%>
            <%= forump(t.id, t.message_count) -%>
          <% end -%>
        </td>

        <td><%= h(t.forummessages.count) -%></td>
        <td><%= link_to sanitize(t.nickname), viewprofile_url(:id => t.user_id) -%> </td>
        <td><%=h t.forummessages.last.user.nickname if t.forummessages %></td>
        <td>
          <% if t.forummessages %>
            <%= t.forummessages.last.created_at.strftime('%d %b %Y %H:%M')  %>
          <% else %>-
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<ul id="topichead">
  <li class="tinfo">
    <%= link_to 'Forum', viewforumindex_url %> > <%= @forum.title %>
  </li>
  <li class="pages">
    <%= will_paginate @topics %>
  </li>
</ul>